### ISSUE TITLE
migrate to the mobiodiv organisation and hosting

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobsim_app#1]
Hey @KatharinaGerstner and @FelixMay how would you guys feel about migrating this repo over to the Mobiodiv organization: https://github.com/mobiodiv

Nothing will really change for how you guys use the repo just where it resides. My thought here is to keep the related repos together for users to discover. I'm going to attempt to host the Rshiny server on my server I'll update this issue with a url if I get it working.

**Comment by FelixMay** [comment]
Hi @dmcglinn and @KatharinaGerstner , I do not mind where the repo is located. So I am fine with your account Katharina, or the MoBiodiv organization

**Comment by dmcglinn** [comment]
Sounds good. @KatharinaGerstner I just invited you to be a contributor to the mobiodiv org.  This may allow you to move the repo yourself (this is done in the settings of the repo) alternatively If you give me admin privileges on the repo then I can move it to mobiodiv.

**Comment by dmcglinn** [comment]
The app is live at this url: 
http://uniola.biology.cofc.edu:3232/mobsim_app/

**Comment by dmcglinn** [comment]
Thanks @KatharinaGerstner for the invite as a contributor. I still am not granted the ability to transfer ownship of the repo. This is easier then I thought though just follow these steps. 
* Log in to github
* navigate to https://github.com/KatharinaGerstner/mobsim_app/settings 
* at the bottom of the page in the "Danger zone" click on "Transfer ownership"
* transfer ownership to the MoBiodiv organization.

**Comment by KatharinaGerstner** [comment]
@dmcglinn I followed the steps. Not sure though it worked.

**Comment by dmcglinn** [comment]
yea it worked!
